import type { AnalysisResult, RiskLevel } from '@/types'
import {
  categoryToLegacy,
  densityFromScore,
  ensureRiskScore,
  recommendationForScore,
  scoreToCategory,
} from './risk'

export { getRiskColor, getRiskBg } from './risk'

/** Crowdsourced / demo points shown on the public pollution map (≥10). */
export const MAP_EXAMPLES = [
  {
    id: 'map-1',
    sourceId: 'map-astana-left',
    locationName: 'Left Bank, Astana',
    waterSource: 'Tap' as const,
    volumeFiltered: 500,
    latitude: 51.1282,
    longitude: 71.4306,
    notes: 'Municipal tap near government district',
    date: '2026-07-12',
    submittedToMap: true,
    possibleSource: 'Possible urban / wastewater influence',
    analysis: ensureRiskScore({
      suspectedParticles: 38,
      fiberCount: 14,
      fragmentCount: 24,
      contaminationDensity: 76,
      riskLevel: 'Medium' as RiskLevel,
      riskScore: 44,
      confidenceScore: 87,
      possibleParticleTypes: ['colored fibers', 'clear fragments'],
    }),
  },
  {
    id: 'map-2',
    sourceId: 'map-esil-riverside',
    locationName: 'Yesil riverside well',
    waterSource: 'Well' as const,
    volumeFiltered: 500,
    latitude: 51.1605,
    longitude: 71.4278,
    notes: 'Shallow well close to the river',
    date: '2026-07-18',
    submittedToMap: true,
    possibleSource: 'Possible urban / wastewater influence',
    analysis: ensureRiskScore({
      suspectedParticles: 92,
      fiberCount: 38,
      fragmentCount: 54,
      contaminationDensity: 184,
      riskLevel: 'High' as RiskLevel,
      riskScore: 71,
      confidenceScore: 90,
      possibleParticleTypes: ['colored fibers', 'clear fragments', 'irregular suspicious fragments'],
    }),
  },
  {
    id: 'map-3',
    sourceId: 'map-baiterek',
    locationName: 'Baiterek area tap',
    waterSource: 'Tap' as const,
    volumeFiltered: 500,
    latitude: 51.1334,
    longitude: 71.4412,
    notes: 'Apartment building kitchen tap',
    date: '2026-07-20',
    submittedToMap: true,
    possibleSource: 'Possible urban pipe / distribution influence',
    analysis: ensureRiskScore({
      suspectedParticles: 24,
      fiberCount: 9,
      fragmentCount: 15,
      contaminationDensity: 48,
      riskLevel: 'Low' as RiskLevel,
      riskScore: 28,
      confidenceScore: 85,
      possibleParticleTypes: ['clear fragments'],
    }),
  },
  {
    id: 'map-4',
    sourceId: 'map-airport',
    locationName: 'Near Nursultan Nazarbayev Airport',
    waterSource: 'Tap' as const,
    volumeFiltered: 500,
    latitude: 51.0222,
    longitude: 71.4669,
    notes: 'Service building tap',
    date: '2026-07-22',
    submittedToMap: true,
    possibleSource: 'Possible urban / wastewater influence',
    analysis: ensureRiskScore({
      suspectedParticles: 61,
      fiberCount: 25,
      fragmentCount: 36,
      contaminationDensity: 122,
      riskLevel: 'Medium' as RiskLevel,
      riskScore: 52,
      confidenceScore: 84,
      possibleParticleTypes: ['colored fibers', 'clear fragments'],
    }),
  },
  {
    id: 'map-5',
    sourceId: 'map-almaty-district',
    locationName: 'Almaty district spring',
    waterSource: 'Spring' as const,
    volumeFiltered: 500,
    latitude: 51.1478,
    longitude: 71.5124,
    notes: 'Community spring after rain',
    date: '2026-07-25',
    submittedToMap: true,
    possibleSource: 'Possible agricultural film influence',
    analysis: ensureRiskScore({
      suspectedParticles: 48,
      fiberCount: 19,
      fragmentCount: 29,
      contaminationDensity: 96,
      riskLevel: 'Medium' as RiskLevel,
      riskScore: 46,
      confidenceScore: 83,
      possibleParticleTypes: ['colored fibers', 'irregular suspicious fragments'],
    }),
  },
  {
    id: 'map-6',
    sourceId: 'map-saryarka',
    locationName: 'Saryarka market well',
    waterSource: 'Well' as const,
    volumeFiltered: 500,
    latitude: 51.1756,
    longitude: 71.4189,
    notes: 'Busy market area well',
    date: '2026-07-28',
    submittedToMap: true,
    possibleSource: 'Possible landfill / waste influence',
    analysis: ensureRiskScore({
      suspectedParticles: 118,
      fiberCount: 52,
      fragmentCount: 66,
      contaminationDensity: 236,
      riskLevel: 'High' as RiskLevel,
      riskScore: 78,
      confidenceScore: 92,
      possibleParticleTypes: ['colored fibers', 'clear fragments', 'irregular suspicious fragments'],
    }),
  },
  {
    id: 'map-7',
    sourceId: 'map-expo',
    locationName: 'EXPO district after filter',
    waterSource: 'After filter' as const,
    volumeFiltered: 500,
    latitude: 51.0891,
    longitude: 71.4163,
    notes: 'Office kitchen post-filter sample',
    date: '2026-07-30',
    submittedToMap: true,
    possibleSource: 'Filtered household water',
    analysis: ensureRiskScore({
      suspectedParticles: 12,
      fiberCount: 4,
      fragmentCount: 8,
      contaminationDensity: 24,
      riskLevel: 'Low' as RiskLevel,
      riskScore: 18,
      confidenceScore: 91,
      possibleParticleTypes: ['clear fragments'],
    }),
  },
  {
    id: 'map-8',
    sourceId: 'map-kosshy',
    locationName: 'Kosshy village borehole',
    waterSource: 'Borehole' as const,
    volumeFiltered: 500,
    latitude: 51.0,
    longitude: 71.35,
    notes: 'Deep borehole, rural outskirts',
    date: '2026-08-01',
    submittedToMap: true,
    possibleSource: 'Source unknown — continue monitoring',
    analysis: ensureRiskScore({
      suspectedParticles: 19,
      fiberCount: 7,
      fragmentCount: 12,
      contaminationDensity: 38,
      riskLevel: 'Low' as RiskLevel,
      riskScore: 26,
      confidenceScore: 86,
      possibleParticleTypes: ['clear fragments'],
    }),
  },
  {
    id: 'map-9',
    sourceId: 'map-industrial',
    locationName: 'Industrial zone south',
    waterSource: 'Well' as const,
    volumeFiltered: 500,
    latitude: 51.095,
    longitude: 71.52,
    notes: 'Well downwind of light industry',
    date: '2026-08-02',
    submittedToMap: true,
    possibleSource: 'Possible industrial discharge influence',
    analysis: ensureRiskScore({
      suspectedParticles: 134,
      fiberCount: 58,
      fragmentCount: 76,
      contaminationDensity: 268,
      riskLevel: 'High' as RiskLevel,
      riskScore: 84,
      confidenceScore: 89,
      possibleParticleTypes: ['colored fibers', 'clear fragments', 'irregular suspicious fragments'],
    }),
  },
  {
    id: 'map-10',
    sourceId: 'map-botanical',
    locationName: 'Botanical garden tap',
    waterSource: 'Tap' as const,
    volumeFiltered: 500,
    latitude: 51.152,
    longitude: 71.398,
    notes: 'Public tap near park',
    date: '2026-08-03',
    submittedToMap: true,
    possibleSource: 'Possible urban pipe / distribution influence',
    analysis: ensureRiskScore({
      suspectedParticles: 33,
      fiberCount: 12,
      fragmentCount: 21,
      contaminationDensity: 66,
      riskLevel: 'Medium' as RiskLevel,
      riskScore: 39,
      confidenceScore: 85,
      possibleParticleTypes: ['colored fibers', 'clear fragments'],
    }),
  },
  {
    id: 'map-11',
    sourceId: 'map-karaganda-rd',
    locationName: 'Karaganda highway farm well',
    waterSource: 'Well' as const,
    volumeFiltered: 500,
    latitude: 51.22,
    longitude: 71.55,
    notes: 'Farm well near plastic mulch fields',
    date: '2026-08-04',
    submittedToMap: true,
    possibleSource: 'Possible agricultural film influence',
    analysis: ensureRiskScore({
      suspectedParticles: 77,
      fiberCount: 31,
      fragmentCount: 46,
      contaminationDensity: 154,
      riskLevel: 'High' as RiskLevel,
      riskScore: 68,
      confidenceScore: 88,
      possibleParticleTypes: ['colored fibers', 'irregular suspicious fragments'],
    }),
  },
  {
    id: 'map-12',
    sourceId: 'map-school',
    locationName: 'School #45 drinking fountain',
    waterSource: 'Tap' as const,
    volumeFiltered: 500,
    latitude: 51.168,
    longitude: 71.462,
    notes: 'School corridor fountain after weekend',
    date: '2026-08-05',
    submittedToMap: true,
    possibleSource: 'Possible urban / wastewater influence',
    analysis: ensureRiskScore({
      suspectedParticles: 29,
      fiberCount: 11,
      fragmentCount: 18,
      contaminationDensity: 58,
      riskLevel: 'Low' as RiskLevel,
      riskScore: 28,
      confidenceScore: 84,
      possibleParticleTypes: ['clear fragments'],
    }),
  },
]

export const MOCK_SAMPLES = [
  {
    id: 'mock-1',
    sourceId: 'src-home-well',
    locationName: 'Home Well',
    waterSource: 'Well' as const,
    volumeFiltered: 500,
    latitude: 51.1801,
    longitude: 71.446,
    notes: 'Baseline rural well',
    date: '2026-06-10',
    submittedToMap: false,
    possibleSource: 'Source unknown — continue monitoring',
    analysis: ensureRiskScore({
      suspectedParticles: 22,
      fiberCount: 8,
      fragmentCount: 14,
      contaminationDensity: 44,
      riskLevel: 'Low' as RiskLevel,
      riskScore: 34,
      confidenceScore: 88,
      possibleParticleTypes: ['clear fragments', 'colored fibers'],
    }),
  },
  {
    id: 'mock-2',
    sourceId: 'src-home-well',
    locationName: 'Home Well',
    waterSource: 'Well' as const,
    volumeFiltered: 500,
    latitude: 51.1801,
    longitude: 71.446,
    notes: 'Follow-up screening',
    date: '2026-06-24',
    submittedToMap: false,
    possibleSource: 'Source unknown — continue monitoring',
    analysis: ensureRiskScore({
      suspectedParticles: 41,
      fiberCount: 16,
      fragmentCount: 25,
      contaminationDensity: 82,
      riskLevel: 'Medium' as RiskLevel,
      riskScore: 47,
      confidenceScore: 86,
      possibleParticleTypes: ['colored fibers', 'irregular fragments'],
      changeSincePrevious: 13,
    }),
  },
  {
    id: 'mock-3',
    sourceId: 'src-home-well',
    locationName: 'Home Well',
    waterSource: 'Well' as const,
    volumeFiltered: 500,
    latitude: 51.1801,
    longitude: 71.446,
    notes: 'Latest home well screening',
    date: '2026-07-08',
    submittedToMap: false,
    possibleSource: 'Possible agricultural film influence nearby',
    analysis: ensureRiskScore({
      suspectedParticles: 98,
      fiberCount: 40,
      fragmentCount: 58,
      contaminationDensity: 196,
      riskLevel: 'High' as RiskLevel,
      riskScore: 72,
      confidenceScore: 91,
      possibleParticleTypes: ['colored fibers', 'clear fragments', 'irregular fragments'],
      changeSincePrevious: 25,
    }),
  },
  {
    id: 'mock-4',
    sourceId: 'src-kitchen-tap',
    locationName: 'Kitchen Tap',
    waterSource: 'Tap' as const,
    volumeFiltered: 500,
    latitude: 51.181,
    longitude: 71.447,
    notes: 'Municipal tap',
    date: '2026-07-05',
    submittedToMap: false,
    possibleSource: 'Possible urban pipe / distribution influence',
    analysis: ensureRiskScore({
      suspectedParticles: 55,
      fiberCount: 20,
      fragmentCount: 35,
      contaminationDensity: 110,
      riskLevel: 'Medium' as RiskLevel,
      riskScore: 48,
      confidenceScore: 84,
      possibleParticleTypes: ['colored fibers', 'clear fragments'],
    }),
  },
  {
    id: 'mock-5',
    sourceId: 'src-after-filter',
    locationName: 'Water after filter',
    waterSource: 'After filter' as const,
    volumeFiltered: 500,
    latitude: 51.181,
    longitude: 71.447,
    notes: 'Post-filter kitchen sample',
    date: '2026-07-06',
    submittedToMap: false,
    possibleSource: 'Filtered household water',
    analysis: ensureRiskScore({
      suspectedParticles: 16,
      fiberCount: 5,
      fragmentCount: 11,
      contaminationDensity: 32,
      riskLevel: 'Low' as RiskLevel,
      riskScore: 24,
      confidenceScore: 90,
      possibleParticleTypes: ['clear fragments'],
    }),
  },
]

export function detectPossibleSource(locationName: string, notes: string): string {
  const combined = `${locationName} ${notes}`.toLowerCase()
  if (/landfill|waste|dump|свалк|отход|полигон/.test(combined)) return 'Possible landfill / waste influence'
  if (/farm|agricultur|field|crop|mulch|ферм|сельск|пол|плёнк|пленк/.test(combined))
    return 'Possible agricultural film influence'
  if (/factor|industrial|industry|plant|discharge|завод|промышл|фабрик/.test(combined))
    return 'Possible industrial discharge influence'
  if (/city|urban|sewage|wastewater|canal|город|канализац|сток|канал/.test(combined))
    return 'Possible urban / wastewater influence'
  return 'Source unknown — continue monitoring'
}

export function runMockAnalysis(
  volumeFiltered: number,
  previousScore: number | null = null,
  biasToward?: 'low' | 'high' | 'mid',
): AnalysisResult {
  let riskScore = Math.floor(Math.random() * 90) + 8
  if (biasToward === 'high') riskScore = Math.floor(Math.random() * 28) + 70
  if (biasToward === 'low') riskScore = Math.floor(Math.random() * 22) + 8
  if (biasToward === 'mid') riskScore = Math.floor(Math.random() * 30) + 32

  riskScore = Math.min(100, Math.max(1, riskScore))
  const screeningCategory = scoreToCategory(riskScore)
  const riskLevel = categoryToLegacy(screeningCategory)
  const particleDensity = densityFromScore(riskScore)

  const suspectedParticles = Math.round(riskScore * 1.4 + Math.random() * 12)
  const fiberCount = Math.floor(suspectedParticles * (0.3 + Math.random() * 0.25))
  const fragmentCount = Math.max(0, suspectedParticles - fiberCount)
  const contaminationDensity = Math.round((suspectedParticles / Math.max(volumeFiltered, 1)) * 1000)
  const confidenceScore = Math.floor(Math.random() * 14) + 82
  const changeSincePrevious = previousScore != null ? riskScore - previousScore : null

  const allTypes = ['colored fibers', 'clear fragments', 'irregular suspicious fragments']
  const count = riskLevel === 'Low' ? 1 : riskLevel === 'Medium' ? 2 : 3

  return {
    riskScore,
    screeningCategory,
    particleDensity,
    suspectedParticles,
    fiberCount,
    fragmentCount,
    contaminationDensity,
    riskLevel,
    confidenceScore,
    possibleParticleTypes: allTypes.slice(0, count),
    recommendation: recommendationForScore(riskScore, changeSincePrevious),
    changeSincePrevious,
  }
}
